services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true #
        bind:
            $locales: "%manuel_translation.locales%"
            $activeLocales: "%manuel_translation.locales%"
            $cataloguesPath: "%manuel_translation.catalogues_path%"
            $backupDir: "%manuel_translation.translations_backup_dir%"
            $cacheDir: "%kernel.cache_dir%"
            $securityRole: "%manuel_translation.security_role%"

    ManuelAguirre\Bundle\TranslationBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'

    ManuelAguirre\Bundle\TranslationBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    ManuelAguirre\Bundle\TranslationBundle\Entity\TranslationRepository: ~