services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true #
        bind:
            $locales: "%manuel_translation.locales%"
            $activeLocales: "%manuel_translation.locales%"
            $cataloguesPath: "%manuel_translation.catalogues_path%"
            $backupDir: "%manuel_translation.translations_backup_dir%"
            $cacheDir: "%kernel.cache_dir%"
            $securityRole: "%manuel_translation.security_role%"

    ManuelAguirre\Bundle\TranslationBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'

    ManuelAguirre\Bundle\TranslationBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    ManuelAguirre\Bundle\TranslationBundle\Entity\TranslationRepository: ~
    ManuelAguirre\Bundle\TranslationBundle\TranslationRepository:
        alias: ManuelAguirre\Bundle\TranslationBundle\Entity\TranslationRepository

when@dev:
    services:
        _defaults:
            autowire: true      # Automatically injects dependencies in your services.
            autoconfigure: true #

        ManuelAguirre\Bundle\TranslationBundle\Translation\DebugTranslator:
            arguments: [ '@ManuelAguirre\Bundle\TranslationBundle\Translation\DebugTranslator.inner' ]
            decorates: translator

        ManuelAguirre\Bundle\TranslationBundle\DataCollector\TranslationDataCollector:
            class: ManuelAguirre\Bundle\TranslationBundle\DataCollector\TranslationDataCollector
            arguments:
                - "@translator"
                - "%manuel_translation.locales%"
            tags:
                -   name: data_collector
                    template: "@ManuelTranslation/DataCollector/translations.html.twig"
                    id: manuel_translations

        ManuelAguirre\Bundle\TranslationBundle\Doctrine\Listener\DumpFilesListener:
            tags:
                - { name: doctrine.event_listener, event: postUpdate }
                - { name: doctrine.event_listener, event: postPersist }
                - { name: doctrine.event_listener, event: postFlush }