services:
    ManuelAguirre\Bundle\TranslationBundle\Synchronization\Synchronizator: "@manuel_translation.synchronizer"
    manuel_translation.synchronizator:
        alias: "manuel_translation.synchronizer"
        public: true
    manuel_translation.synchronizer:
        class: ManuelAguirre\Bundle\TranslationBundle\Synchronization\Synchronizator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@manuel_translation.translations_repository"
            - "@filesystem"
            - "%kernel.cache_dir%"
            - "%manuel_translation.locales%"
            - "%manuel_translation.translations_backup_dir%"