<?php

namespace ManuelAguirre\Bundle\TranslationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TranslationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationLogRepository extends EntityRepository
{
    public function getAllByTranslation($translation)
    {
        return $this->createQueryBuilder('tl')
            ->where('tl.translation = :translation')
            ->setParameter('translation', $translation)
            ->orderBy('tl.id', 'DESC')
            ->getQuery()
            ->getArrayResult();
    }
}
