<?php

namespace ManuelAguirre\Bundle\TranslationBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * TranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationRepository extends EntityRepository
{
    public function getAllQueryBuilder($search = null, $domain = null,
        $onlyConflicted = null, $onlyChanged = null, $inactives = false)
    {
        $query = $this->createQueryBuilder('translation')
            ->orderBy('translation.active DESC, translation.domain,translation.code');

        if ($inactives) {
            $query->andWhere('translation.active = false');
        }

        if (null !== $search) {
            $part = $query->expr()->orX()
                ->add('translation.code LIKE :search')
                ->add('translation.files LIKE :search')
                ->add('translation.values LIKE :search');

            $query->andWhere($part)
                ->setParameter('search', "%$search%");
        }

        if (null !== $domain) {
            $query->andWhere('translation.domain IN (:domain)')
                ->setParameter('domain', $domain);
        }

        if (null != $onlyConflicted) {
            $query->andWhere('translation.conflicts = true');
        }

        if (null != $onlyChanged) {
            $query->andWhere('translation.isChanged = true');
        }

        return $query;
    }

    public function getAll($search = null, $domain = null,
        $onlyConflicted = null, $onlyChanged = null)
    {
        return $this->getAllQueryBuilder($search, $domain, $onlyConflicted, $onlyChanged)
            ->getQuery()
            ->getArrayResult();
    }

    public function getAllChanged()
    {
        return $this->getAllQueryBuilder(null, null, null)
            ->andWhere('translation.isChanged = true')
            ->getQuery()
            ->getArrayResult();
    }

    public function getAllChangedWithoutConflicts()
    {
        return $this->getAllQueryBuilder(null, null, null)
            ->andWhere('translation.isChanged = true')
            ->andWhere('translation.conflicts = false')
            ->getQuery()
            ->getResult();
    }

    public function getAllWithoutConflicts()
    {
        return $this->getAllQueryBuilder(null, null, null)
            ->andWhere('translation.conflicts = false')
            ->getQuery()
            ->getResult();
    }

    public function getAllWithConflicts()
    {
        return $this->getAllQueryBuilder(null, null, null)
            ->andWhere('translation.conflicts = true')
            ->getQuery()
            ->getResult();
    }

    public function getAllEntities($search = null, $domain = null)
    {
        return $this->getAllQueryBuilder($search, $domain)
            ->getQuery()
            ->getResult();
    }

    public function getActiveTranslations()
    {
        return $this->createQueryBuilder('translation')
            ->select('translation.code, translation.domain, translation.values, translation.files, translation.hash')
            ->orderBy('translation.code')
            ->andWhere('translation.active = true')
            ->getQuery()
            ->getArrayResult();
    }

    public function codeExists($code)
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t.code)')
            ->where('t.code = :code')
            ->setParameter('code', $code)
            ->getQuery()
            ->getSingleScalarResult() > 0;
    }

    public function saveTranslation(Translation $entity, $flush = true)
    {
        $entity->setLocalEditions($entity->getLocalEditions() + 1);
        $entity->setIsChanged(true);

        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function getExistentDomains()
    {
        $result = $this->createQueryBuilder('t')
            ->select('t.domain')
            ->addGroupBy('t.domain')
            ->getQuery()
            ->getScalarResult();

        $domains = array();

        foreach ($result as $item) {
            $domains[$item['domain']] = $item['domain'];
        }

        return $domains;
    }

    public function inactiveByDomainAndCodes($domain, $codes)
    {
        return $this->createQueryBuilder('t')
            ->update('ManuelTranslationBundle:Translation', 't')
            ->set('t.active', 'false')
            ->where('t.domain = :domain')
            ->andWhere('t.code IN (:codes)')
            ->andWhere('t.autogenerated = true')
            ->andWhere('t.active = true')
            ->setParameter('domain', $domain)
            ->setParameter('codes', (array) $codes)
            ->getQuery()
            ->execute();
    }

    public function hasConflicts()
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(t.id)')
            ->where('t.conflicts = true')
            ->getQuery()
            ->getSingleScalarResult() > 0;
    }

    public function getOneArrayByCodeAndDomain($code, $domain)
    {
        return $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.domain = :domain')
            ->andWhere('t.code = :code')
            ->setParameter('domain', $domain)
            ->setParameter('code', $code)
            ->getQuery()
            ->getOneOrNullResult(Query::HYDRATE_ARRAY);
    }
}
