<template>

<trans-filter  :domains="domains"></trans-filter>

<trans-item v-for="item in items" :item="item" :locales.once="locales"></trans-item>

</template>

<script>
import Vue from 'vue'
import TransItem from './TransItem.vue'
import TransFilter from './TransFilter.vue'
import VueResource from 'vue-resource'

Vue.use(VueResource)

export default {
	data () {
		return {
            items: {},
            // locales: TranslationData.locales, //this.getLocales(),
            // domains: TranslationData.domains, //this.getDomains(),
            locales: this.getLocales(),
            domains: this.getDomains(),
        }
	},

    ready () {
        this.resource = this.$resource(this.getTranslationApiUrl() + '{id}')
        //this.resource = this.$resource(TranslationData.baseUrlApi + '{id}')

        this.getTranslations()
    },

    methods: {
        getTranslations () {
            return this.resource.get().then((res) => {
                this.$set('items', res.json());
            })
        },

        save (item, success, error, complete) {
            let promise = null
            if (item.id){
                promise = this.resource.update({id: item.id}, item)
            }else{
                promise = this.resource.save({id: item.id}, item)   
            }

            promise.then(response => {
                let data = response.json()
                this.items.$set(this.items.indexOf(item), data); // Actualizamos el item con la nueva data
                success && success(data)

                this.addDomain(data.domain)
            }, response => {
                error && error(response)
            })
        },

        add () {
            this.items.unshift({
                id: null,
                active: true,
                autogenerated: false,
                code: null,
                domain: 'messages',
                files: [],
                values: {},
                new: false,
            })
        },

        remove (item) {
            this.items.$remove(item)
            // todo ver si se van a eliminar elementos de la bd
        } 
    },

    events: {
        'save-item' (item, success, error) {
            this.save(item, success, error)
        },
        'add-item' () {
            this.add()
        },
        'remove-item' (item) {
            this.remove (item)
        }
    },

    components: {TransItem, TransFilter}
}
</script>