<template>
<div class="translation-item">
	<div class="panel panel-default">
		<div class="panel-heading">
			<trans-item-header 
			:code.once="item.code" :domain.once="item.domain"
			:autogenerated.once="item.autogenerated" :active="item.active"
			@click="toggleEdition()"></trans-item-header>
		</div>
		<div class="panel-body"> 
			<div class="row">
				<div class="col-sm-12">
					<trans-item-values :values.sync="item.values" 
					:locales="locales" :editing.sync="editing">
						<div slot="extra-buttons">
							<button type="button" v-show="showFilesVisible" class="btn btn-default btn-xs" @click="visibleFiles = true">Show Files</button>

							<button type="button" v-show="hideFilesVisible" class="btn btn-default btn-xs" @click="visibleFiles = false">Hide Files</button>
						</div>
					</trans-item-values>
				</div>
				<div class="col-sm-12" v-if="hasFiles" v-show="editing || visibleFiles">
					<trans-item-files :files="item.files"></trans-item-files>
				</div>
			</div>
		</div>
	</div>
	 <!-- {{ item|json }} -->
</div>
</template>

<script>
import Vue from 'vue'
import TransItemValues from './TransItemValues.vue'
import TransItemFiles from './TransItemFiles.vue'
import TransItemHeader from './TransItemHeader.vue'

export default {
	props: {
		item: {
			required: true,
			type: Object
		},
		locales: {required: true, type: [Array, Object]}
	},

	computed: {
		hasFiles () {
			return this.item.files.length > 0
		},
		showFilesVisible () {
			return this.hasFiles && !this.visibleFiles && !this.editing
		},
		hideFilesVisible () {
			return this.hasFiles && this.visibleFiles && !this.editing
		}
	},

	data () {
		return {
			editing: false,
			visibleFiles: false,
		}
	},

	methods: {
		activateEdition () {
			this.editing = true
			this.$broadcast('activate-edition', this.item, this.values)
		},
		deactivateEdition () {
			this.editing = false
			this.$broadcast('deactivate-edition', this.item, this.values)
		},
		toggleEdition () {
			if (this.editing){
				this.deactivateEdition()
			}else{
				this.activateEdition()
			}
		},
	},

	components: {TransItemValues, TransItemFiles, TransItemHeader}
}
</script>

<style>
	
</style>