<template>
    <!--<div class="translation-item col-xs-12" v-loading="isLoading" :loading-options="{text: $t('label.loading') + '...'}">-->
    <div class="translation-item col-xs-12">
        <div class="panel panel-default" :class="{'translation-inactive': !translation.active}">
            <div class="panel-heading">

                <trans-item-header
                        :code="translation.code"
                        :domain="translation.domain"
                        :autogenerated.once="translation.autogenerated"
                        :active="translation.active"
                        :editing="editing"
                        :onChangeData="updateData"
                ></trans-item-header>

            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-9 col-md-10">
                        <trans-item-values
                                :values="translation.values"
                                :locales="locales"
                                :editing="editing"
                                :active="translation.active"
                                :is-new="isNew"
                                :onChangeData="updateData"
                        ></trans-item-values>
                    </div>

                    <div class="col-sm-3 col-md-2">
                        <trans-item-buttons
                                :values="translation.values"
                                :locales="locales"
                                :editing="editing"
                                :active="translation.active"
                                :is-new="isNew"
                                :onSave="handleSave"
                                :onEdit="initEdition"
                                :onCancelEdit="cancelEdition"
                                :onActivate="handleActivate"
                                :onDeactivate="handleDeactivate"
                        ></trans-item-buttons>
                    </div>

                    <!--<div slot="extra-buttons">-->
                    <!--<button type="button" v-show="editing && isNew" class="btn btn-danger btn-xs" @click="remove()">{{ $t('label.cancel_reation') }}</button>-->

                    <!--<button type="button" v-show="showFilesVisible" class="btn btn-default btn-xs" @click="visibleFiles = true">Show Files</button>-->

                    <!--<button type="button" v-show="hideFilesVisible" class="btn btn-default btn-xs" @click="visibleFiles = false">Hide Files</button>-->
                    <!--</div>-->
                    <!--<div class="col-sm-12" v-if="hasFiles" v-show="editing || visibleFiles">-->
                    <!--<trans-item-files :files="item.files"></trans-item-files>-->
                    <!--</div>-->
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    import Vue from 'vue'
    import TransItemHeader from './TransItemHeader.vue'
    import TransItemValues from './TransItemValues.vue'
    import TransItemButtons from './TransItemButtons.vue'

    /*
     import TransItemFiles from './TransItemFiles.vue'
     import AlertIcon from '../directives/AlertIcon.vue'
     import Loading from 'vue-loading'
     import TransValidation from '../../js/TransValidation.js'
     */
    Vue.filter('defaultMessage', function (value) {
        return value || '[' + Vue.t('label.empty_value') + ']'
    })

    export default {
        props: {
            index: {required: true, type: [Number, String]},
            translation: {required: true, type: Object},
            locales: {type: [Array, Object], required: true},
            domains: {type: [Array, Object], required: true},
            changeData: {type: Function, required: true},
            activate: {type: Function, required: true},
            deactivate: {type: Function, required: true},
            save: {type: Function, required: true},
        },

        data () {
            return {
                editing: false,
                visibleFiles: false,
                isLoading: false,
                isNew: false,
                originalValues: {},
                originalCode: '',
//            validator: new TransValidation(this.item),
            }
        },

        created () {
            console.log('Creado Componente TransItem', this.index)
        },

        methods: {
            initEdition () {
                this.editing = true
                this.originalValues = Object.assign({}, this.translation.values)
                this.originalCode = this.translation.code
            },
            cancelEdition () {
                this.editing = false

                this.changeData(this.index, {
                    code: this.originalCode,
                    values: this.originalValues,
                })
            },
            handleActivate() {
                this.activate(this.index)
                this.save(this.index)
            },
            handleDeactivate() {
                this.deactivate(this.index)
                this.save(this.index)
            },
            handleSave() {
                this.save(this.index)
            },
            updateData(data) {
                this.changeData(this.index, data)
            },
        },

        components: {TransItemValues, TransItemButtons, /*TransItemFiles,*/ TransItemHeader},
        //directives: {Loading, AlertIcon},

    }

</script>

<style>
    .glyphicon.label:empty {
        display: inline;
    }

    .translation-item .alert {
        padding: 5px;
    }

    .translation-item .panel {
        margin-bottom: 10px;
    }

    .translation-item .panel-warning .panel-heading .text-muted {
        color: #FFFFFF;
    }

    .translation-item .panel-heading {
        padding: 6px 15px;
    }

    .translation-item .panel-body {
        padding: 10px;
    }

    .translation-item .translation-item-value {
        margin-bottom: 5px;
    }

    .translation-inactive .panel-heading {
        opacity: 0.4
    }

    .translation-inactive .panel-body {
        opacity: 0.7
    }


</style>