<template>
	<div class="row trans-item-header">
		<div class="col-sm-6">
			<h3 class="panel-title">
				{{ code }}
				<slot name="message"></slot>
			</h3>
		</div>
		<div class="col-sm-6 text-right">
			<div class="row">
				<div class="col-sm-5 text-left"><small class="text-muted">{{ domain }}</small></div>
				<div class="col-sm-4"><b>Autogenerated:</b> {{ autogenerated | boolean }}</div>
				<div class="col-sm-3"><b>Active:</b> {{ active | boolean }}</div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	props: {
		code: {required: true},
		domain: {required: true},
		autogenerated: {required: true},
		active: {required: true},
	}
}
</script>

<style>
	.trans-item-header {
		cursor: pointer;
	}
</style>