<template>
	<div class="row trans-item-header">
		<div class="col-sm-6">
			<h3 class="panel-title" v-if="!isNew">
				{{ code | defaultMessage }}
				<slot name="message"></slot>
			</h3>
			<input v-if="isNew" type="text" class="form-control input-sm" v-model="code">
		</div>
		<div class="col-sm-6 text-right">
			<div class="row">
				<div class="col-sm-5 text-left">
					<small class="text-muted" v-if="!isNew">{{ domain }}</small>
					<domain-form v-if="isNew" :domain.sync="domain"></domain-form>
				</div>
				<div class="col-sm-4"><b>{{ $t('label.autogenerated') }}:</b> {{ autogenerated | boolean }}</div>
				<div class="col-sm-3"><b>{{ $t('label.active') }}:</b> {{ active | boolean }}</div>
			</div>
		</div>
	</div>
</template>

<script>
import DomainForm from './DomainForm.vue'

export default {
	props: {
		code: {required: true, twoWay: true},
		domain: {required: true, twoWay: true},
		autogenerated: {required: true},
		active: {required: true},
		isNew: {required: true, type: Boolean},
	},

	components: {DomainForm},
}
</script>

<style>
	.trans-item-header {
		cursor: pointer;
	}
</style>