<template>
<div class="translation-item" v-loading="isLoading" :loading-options="{text: $t('label.loading') + '...'}">
	<div class="panel panel-default" :class="{'translation-inactive': !item.active}">
		<div class="panel-heading">
			<trans-item-header 
			:code.sync="item.code" :domain.sync="item.domain"
			:autogenerated.once="item.autogenerated" :active="item.active"
			@click="!isNew && toggleEdition()" :is-new="isNew">

				<span slot="message">
					<span class="glyphicon glyphicon-ok label label-success" v-alert-icon.literal="save-success">
						{{ $t('alert.save.success') }}
					</span>
					<span class="glyphicon glyphicon-remove label label-danger" v-alert-icon.literal="save-error">
						{{ $t('alert.save.error') }}						
					</span>
				</span>

			</trans-item-header>
		</div>
		<div class="panel-body"> 
			<div class="row">
				<div class="col-sm-12">
					<trans-item-values :values.sync="item.values" 
					:locales="locales" :editing.sync="editing" :active="item.active" :is-new="isNew">

						<div slot="extra-buttons">
							<button type="button" v-show="editing && isNew" class="btn btn-danger btn-xs" @click="remove()">{{ $t('label.cancel_reation') }}</button>

							<button type="button" v-show="showFilesVisible" class="btn btn-default btn-xs" @click="visibleFiles = true">Show Files</button>

							<button type="button" v-show="hideFilesVisible" class="btn btn-default btn-xs" @click="visibleFiles = false">Hide Files</button>
						</div>

					</trans-item-values>
				</div>
				<div class="col-sm-12" v-if="hasFiles" v-show="editing || visibleFiles">
					<trans-item-files :files="item.files"></trans-item-files>
				</div>
			</div>
		</div>
	</div>

</div>
</template>

<script>
import Vue from 'vue'
import TransItemValues from './TransItemValues.vue'
import TransItemFiles from './TransItemFiles.vue'
import TransItemHeader from './TransItemHeader.vue'
import AlertIcon from '../directives/AlertIcon.vue'
import Loading from 'vue-loading';

Vue.filter('defaultMessage', function(value) {
	return value || '[' + Vue.t('label.empty_value') + ']'
})

export default {
	props: {
		item: {
			required: true,
			type: Object
		},
		locales: {required: true, type: [Array, Object]}
	},

	computed: {
		hasFiles () {
			return this.item.files.length > 0
		},
		showFilesVisible () {
			return this.hasFiles && !this.visibleFiles && !this.editing
		},
		hideFilesVisible () {
			return this.hasFiles && this.visibleFiles && !this.editing
		},
		isNew () {
			return null === this.item.id
		}
	},

	data () {
		return {
			editing: false,
			visibleFiles: false,
			isLoading: false,
		}
	},

	ready() {
		if(this.isNew){
			// Si no hay id es porque es un item nuevo, por lo que activamos la edición por defecto:
			this.activateEdition()
		}
	},

	methods: {
		activateEdition () {
			this.editing = true
			this.$broadcast('activate-edition', this.item, this.values)
		},
		deactivateEdition () {
			this.editing = false
			this.$broadcast('deactivate-edition', this.item, this.values)
		},
		toggleEdition () {
			if (this.editing){
				this.deactivateEdition()
			}else{
				this.activateEdition()
			}
		},
		save () {
			this.isLoading = true
			this.$dispatch('save-item', this.item, this.onSaveSuccess, this.onSaveError)
		},
		onSaveSuccess () {
			this.onSaveCompleted()
			this.$emit('alert-icon:show', 'save-success')
		},
		onSaveError () {
			this.onSaveCompleted()
			this.$emit('alert-icon:show', 'save-error')
		},
		onSaveCompleted () {
			this.editing = false
			this.isLoading = false			
		},
		remove () {
			if (!this.isNew){
				return;
			}

			this.$dispatch('remove-item', this.item)
		}
	},

	events: {
		'update-values' () {
			// cuando se actualizen los valores, guardamos el registro
			this.save()
		},
		'activate-translation' () {
			this.item.active = true
			this.save()
		},
		'deactivate-translation' () {
			this.item.active = false
			this.save()
		}
	},

	components: {TransItemValues, TransItemFiles, TransItemHeader},
	directives: {Loading, AlertIcon},

}
</script>

<style>
	.glyphicon.label:empty { display: inline; }

	.translation-item .alert{ padding: 5px; }
	.translation-item .panel-warning .panel-heading .text-muted{ color: #FFFFFF; }

	.translation-inactive .panel-heading{opacity: 0.4}
	.translation-inactive .panel-body{opacity: 0.7}

</style>