<?php
/*
 * This file is part of the Manuel Aguirre Project.
 *
 * (c) Manuel Aguirre <programador.manuel@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ManuelAguirre\Bundle\TranslationBundle\Controller;

use ManuelAguirre\Bundle\TranslationBundle\Entity\Translation;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


/**
 * @author Manuel Aguirre <programador.manuel@gmail.com>
 */
class SyncController extends Controller
{
    /**
     * @Route("/generate-file", name="manuel_translation_generate_file")
     */
    public function generateFilesAction()
    {
        if($this->get('manuel_translation.synchronizator')->generateFile()){
            $this->addFlash('success', $this->get('translator')->trans('update_file_complete_flash', array(), 'ManuelTranslationBundle'));
        }else{
            $this->addFlash('warning', $this->get('translator')->trans('local_hash_update_of_range', array(), 'ManuelTranslationBundle'));
        }

        return $this->redirectToRoute('manuel_translation_list');
    }

    /**
     * @Route("/sync", name="manuel_translation_load_from_file")
     */
    public function syncAction()
    {
        $result = $this->get('manuel_translation.synchronizator')->sync();

        $filenameTemplate = $this->container->getParameter('manuel_translation.filename_template');

        return $this->render('@ManuelTranslation/Sync/resolve_conflicts.html.twig', array(
            'news' => $result->getNews(),
            'updates' => $result->getUpdated(),
            'conflicted_items' => $result->getConflictItems(),
        ));
    }

    /**
     * @Route("/resolve-conflict/{id}",
     *  name="manuel_translation_resolve_conflict"
     * )
     */
    public function resolveConflictAction(Translation $translation, Request $request)
    {
        $values = $request->request->get('values', array());
        $files = $request->request->get('files', array());
        $hash = $request->request->get('hash');
        $active = $request->request->get('active');
        $new = $request->request->get('new');
        $autogenerated = $request->request->get('autogenerated');
        $lastChanged = $request->request->get('last_changed');

        $this->get('manuel_translation.synchronizator')->updateTranslation(
            $translation, $values, $files, $hash, $active, $new, $autogenerated, $lastChanged
        );
        $this->getDoctrine()->getManager()->flush();

        return new Response('Ok');
    }

    /**
     * @Route("/resolve-conflict-done",
     *  name="manuel_translation_resolve_conflict_done"
     * )
     */
    public function doneSyncAction()
    {
        $this->get('manuel_translation.synchronizator')->markSyncAsDone();

        return $this->redirectToRoute('manuel_translation_list');
    }
}