<template>
    <div class="row trans-item-header">
        <div class="col-sm-6">
            <h3 class="panel-title" v-if="!isNew && !editing">
                {{ code | defaultMessage }}
                <slot name="message"></slot>
            </h3>

            <div v-else>
                <input type="text"
                       class="form-control input-sm"
                       v-model.lazy="codeValue"
                       minlength="3"
                       ref="codeInput"
                       @blur="changeCode">
                <!--<p v-show="errors.required" class="text-danger">{{ $t('error.translation.code.required') }}</p>-->
                <!--<p v-show="errors.minlength" class="text-danger">{{ $t('error.translation.code.minlength') }}</p>-->
            </div>
        </div>
        <div class="col-sm-6 text-right">
            <div class="row">
                <div class="col-sm-5 text-left">
                    <small class="text-muted" v-if="!editing">{{ domain }}</small>
                    <SelectDomain v-else
                                   :domain="domain"
                                   :existentDomains="existentDomains"
                                   :onUpdate="changeDomain"
                    ></SelectDomain>
                </div>
                <div class="col-sm-4"><b>{{ $t('label.autogenerated') }}:</b> {{ autogenerated | boolean }}</div>
                <div class="col-sm-3"><b>{{ $t('label.active') }}:</b> {{ active | boolean }}</div>
            </div>
        </div>
    </div>
</template>

<script>
    import SelectDomain from './SelectDomain.vue'
    //import TransValidation from '../../js/TransValidation'

    export default {
        props: {
            code: {required: true, type: String},
            domain: {required: true, type: String},
            autogenerated: {required: true, type: Boolean},
            active: {required: true, type: Boolean},
            editing: {required: true, type: Boolean},
            onChangeData: {required: true, type: Function},
            existentDomains: {required: true, type: [Object, Array]},
//        validator: {required: true, type: TransValidation},
        },

        data() {
            return {
                isNew: false,
            }
        },

        computed: {
            errors () {
//            return this.validator.getErrors('code')
            },
            codeValue () {
                return this.code
            },
        },

        methods: {
            changeCode () {
                this.onChangeData({
                    code: this.$refs.codeInput.value
                })
            },
            changeDomain (domain) {
                this.onChangeData({domain})
            },
        },

        components: {SelectDomain},
    }
</script>

<style>
    .trans-item-header {
        cursor: pointer;
    }
</style>