<template>
    <div class="translation-item col-xs-12">
        <!--<div class="panel panel-default" :class="{'translation-inactive': !translation.active}">-->
        <Panel>
            <div slot="header">
                <ItemHeader
                        :code="translation.code"
                        :domain="translation.domain"
                        :existentDomains="domains"
                        :autogenerated.once="translation.autogenerated"
                        :active="translation.active"
                        :editing="editing"
                        :onChangeData="updateData"
                ></ItemHeader>
            </div>
            <div slot="body">
                <div class="row">
                    <div class="col-sm-9 col-md-10">

                        <div v-if="editing && hasErrors">
                            <p v-show="hasError('code.required')" class="text-danger">
                                {{ $t('error.translation.code.required') }}
                            </p>
                            <p v-show="hasError('code.minlength')" class="text-danger">
                                {{ $t('error.translation.code.minlength') }}
                            </p>
                        </div>

                        <ItemValues
                                :values="translation.values"
                                :locales="locales"
                                :editing="editing"
                                :active="translation.active"
                                :onChangeData="updateData"
                        ></ItemValues>

                        <ItemFiles :files="translation.files" v-if="visibleFiles"></ItemFiles>
                    </div> 

                    <div class="col-sm-3 col-md-2">
                        <ItemButtons
                                :hasErrors="hasErrors"
                                :values="translation.values"
                                :locales="locales"
                                :editing="editing"
                                :active="translation.active"
                                :is-new="isNew"
                                :onSave="handleSave"
                                :onEdit="initEdition"
                                :onCancelEdit="cancelEdition"
                                :onActivate="handleActivate"
                                :onDeactivate="handleDeactivate">

                            <Btn size="xs" v-show="showFilesVisible" @click.prevent.native="visibleFiles = true">
                                {{ $t('label.show_files') }}
                            </Btn>
                            <Btn size="xs" v-show="hideFilesVisible" @click.prevent.native="visibleFiles = false">
                                {{ $t('label.hide_files') }}
                            </Btn>

                        </ItemButtons>
                    </div>
                </div>
            </div>
        </Panel>
    </div>
</template>

<script>
    import Vue from 'vue'
    import _ from 'lodash'
    import ItemHeader from 'components/TransItem/Header.vue'
    import ItemValues from 'components/TransItem/Values.vue'
    import ItemButtons from 'components/TransItem/Buttons.vue'
    import ItemFiles from 'components/TransItem/Files.vue'
    import Panel from 'components/Generic/Panel.vue'
    import Btn from 'components/Generic/Button.vue'
    import TransValidation from 'TransValidation'

    Vue.filter('defaultMessage', function (value) {
        return value || '[' + Vue.t('label.empty_value') + ']'
    })

    export default {
        props: {
            index: {required: true, type: [Number, String]},
            translation: {required: true, type: Object},
            locales: {type: [Array, Object], required: true},
            domains: {type: [Array, Object], required: true},
            changeData: {type: Function, required: true},
            activate: {type: Function, required: true},
            deactivate: {type: Function, required: true},
            save: {type: Function, required: true},
            remove: {type: Function, required: true},
        },

        data () {
            return {
                editing: false,
                visibleFiles: false,
                originalValues: {},
                originalCode: '',
                errors: {},
            }
        },

        computed: {
            isNew () {
                return null == this.translation.id
            },
            showFilesVisible() {
                return !this.visibleFiles && this.translation.files.length > 0
            },
            hideFilesVisible() {
                return this.visibleFiles
            },
            validator () {
                return new TransValidation(this.translation)
            },
            hasErrors () {
                return !_.isEmpty(this.errors)
            },
        },

        watch: {
            translation() {
                this.validate()
            }
        },

        beforeUpdated () {
            this.validate()
        },

        created () {
//            console.log('Creado Componente TransItem', this.index)
            if (this.isNew) {
                this.initEdition()
            }
        },

        destroyed () {
            console.log('Eliminado Componente TransItem', this.index)
        },

        methods: {
            initEdition () {
                this.editing = true
                this.originalValues = Object.assign({}, this.translation.values)
                this.originalCode = this.translation.code

                this.validate()
            },
            cancelEdition () {
                if (this.isNew) {
                    // Si es una nueva traduccion, la borramos
                    this.remove(this.index)

                    return
                }

                this.editing = false

                this.changeData(this.index, {
                    code: this.originalCode,
                    values: this.originalValues,
                })
            },
            handleActivate() {
                return this.activate(this.index)
            },
            handleDeactivate() {
                return this.deactivate(this.index)
            },
            handleSave() {
                if(this.hasErrors){
                    return Promise.reject()
                }

                let promise = this.save(this.index);

                promise.then(() => {
                    this.editing = false
                })

                return promise
            },
            updateData(data) {
                this.changeData(this.index, data)
            },
            hasError(path) {
                return _.get(this.errors, path, false)
            },
            validate() {
                this.errors = this.validator.validate()
            }
        },
        components: {ItemValues, ItemButtons, ItemFiles, ItemHeader, Panel, Btn},
    }

</script>

<style>
    .glyphicon.label:empty {
        display: inline;
    }

    .translation-item .alert {
        padding: 5px;
    }

    .translation-item .panel {
        margin-bottom: 10px;
    }

    .translation-item .panel-warning .panel-heading .text-muted {
        color: #FFFFFF;
    }

    .translation-item .panel-heading {
        padding: 6px 15px;
    }

    .translation-item .panel-body {
        padding: 10px;
    }

    .translation-item .translation-item-value {
        margin-bottom: 5px;
    }

    .translation-inactive .panel-heading {
        opacity: 0.4
    }

    .translation-inactive .panel-body {
        opacity: 0.7
    }


</style>